"""
Django settings for phytolean project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import faulthandler
import io
import logging
import os
import signal

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import socket
import sys
import traceback
from pathlib import Path

import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = [
    '127.0.0.1',
    '178.128.29.29',
    'phytolean.co.za',
    'www.phytolean.co.za',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps
    'main.apps.MainConfig',
    # external
    'crispy_forms',
    'crispy_bootstrap5',
    'captcha',
    'django_extensions',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'phytolean.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'main' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'phytolean.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

APPEND_SLASH = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'


# logging
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)
if sys.stdout.encoding != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

# faulthandler catches segfaults / fatal signals that bypass Python logging
_fault_log = open(LOG_DIR / 'fault.log', 'a', buffering=1)
faulthandler.enable(file=_fault_log, all_threads=True)
# gunicorn sends SIGTERM on worker timeout; dump every thread's stack first
# faulthandler.register is POSIX-only; skip on Windows
if hasattr(faulthandler, 'register'):
    for _sig in (signal.SIGTERM, signal.SIGABRT):
        try:
            faulthandler.register(_sig, file=_fault_log, all_threads=True, chain=True)
        except (ValueError, OSError):
            pass

# catch anything raised before/outside Django's request cycle (boot errors, threads)
def _log_uncaught(exc_type, exc, tb):
    msg = ''.join(traceback.format_exception(exc_type, exc, tb))
    try:
        logging.getLogger('uncaught').critical('Uncaught exception:\n%s', msg)
    except Exception:
        pass
    _fault_log.write(f'UNCAUGHT {msg}\n')
    _fault_log.flush()
sys.excepthook = _log_uncaught

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)-8s %(name)s %(message)s {%(filename)s:%(lineno)d}',
        },
        'compact': {
            'format': '%(asctime)s %(levelname)-8s %(name)s %(message)s',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(LOG_DIR / 'app.log'),
            'when': 'midnight',
            'backupCount': 14,
            'delay': False,
            'formatter': 'standard',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'stream': sys.stderr,
            'formatter': 'compact',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gunicorn.error': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# settings are imported before Django applies LOGGING, so write a boot marker
# directly to the log file. If this line never appears, the worker didn't even
# finish importing settings (check gunicorn/systemd stdout, not Django logs).
with open(LOG_DIR / 'app.log', 'a', encoding='utf-8') as _boot:
    import datetime as _dt
    _boot.write(
        f'{_dt.datetime.now().isoformat()} BOOT     settings imported '
        f'pid={os.getpid()} argv={sys.argv} debug={DEBUG}\n'
    )

# crispy forms
CRISPY_TEMPLATE_PACK = 'bootstrap5'
CRISPY_FAIL_SILENTLY = not DEBUG

CAPTCHA_TEST_MODE = bool(len(sys.argv) > 1 and sys.argv[1] == 'test')
CAPTCHA_IMAGE_SIZE = (300, 75)
CAPTCHA_FONT_SIZE = 40

# EMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.smtp2go.com'
DEFAULT_FROM_EMAIL = 'PhytoLean <info@phytolean.co.za>'
DEFAULT_REPLY_EMAIL = 'PhytoLean <phytolean@gmail.com>'
DEFAULT_TO_EMAILS = ['PhytoLean <phytolean@gmail.com>', 'Jaco <jacoj82@gmail.com>']
EMAIL_HOST_USER = 'phytolean'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_PORT = 465
EMAIL_TIMEOUT = 10

EMAIL_API_URL = env('EMAIL_API_URL')
EMAIL_API_KEY = env('EMAIL_API_KEY')

SCHEDULE_ENABLED = True

# payfast
PAYFAST_MERCHANT_ID = env.int('PAYFAST_MERCHANT_ID')
PAYFAST_MERCHANT_KEY = env.str('PAYFAST_MERCHANT_KEY')
PAYFAST_PROCESS_URL = env.str('PAYFAST_PROCESS_URL')
PAYFAST_PASSPHRASE = env.str('PAYFAST_PASSPHRASE')
PAYFAST_VALIDATE_URL = env.str('PAYFAST_VALIDATE_URL')
