[project]
name = "phytolean"
version = "1.0.0"
description = "Nutritional health and wellness website"
requires-python = "==3.11.*"
dependencies = [
    "beautifulsoup4",
    "crispy-bootstrap5",
    "django",
    "django-crispy-forms",
    "django-environ",
    "django-import-export",
    "django-simple-captcha",
    "django-extensions",
    "gunicorn",
    "lxml",
    "mailjet_rest",
    "pandas",
    "plotly",
    "pytz",
    "unidecode",
    "requests",
    "retry",
]

[tool.setuptools]
packages = []

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"
