# Generated by Django 3.2.8 on 2021-12-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
