# Generated by Django 3.2.8 on 2021-12-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211215_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='has_sent_appointment_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discovery',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20, verbose_name='Your biological sex'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='discovery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.discovery'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('denied', 'denied'), ('booked', 'booked'), ('completed', 'completed')], default='new', max_length=30),
        ),
    ]
