# Generated by Django 3.2.8 on 2022-05-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211227_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='diagnosis',
            field=models.TextField(default='a', verbose_name='Have you been diagnosed with a condition (diagnosis)?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discovery',
            name='medications',
            field=models.TextField(default='a', verbose_name='List the medications or supplements you are currently using:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discovery',
            name='vaccinations',
            field=models.TextField(default='a', verbose_name='Have you received the covid vaccinations? Which brand and how many?'),
            preserve_default=False,
        ),
    ]
