# Generated by Django 3.2.8 on 2023-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220517_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField()),
                ('prefix', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=50)),
                ('ethnicity', models.CharField(choices=[('African', 'African'), ('Asian', 'Asian'), ('Latin', 'Latin'), ('Pacific', 'Pacific'), ('Caucasian', 'Caucasian'), ('Other', 'Other')], default='Caucasian', max_length=50)),
                ('cancer', models.BooleanField()),
                ('diseases', models.CharField(blank=True, max_length=250, null=True)),
                ('origin', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=50)),
                ('practitioner', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Yes, and is open for collaboration', 'Yes, and is open for collaboration')], max_length=50)),
                ('diet', models.CharField(max_length=250)),
                ('intention', models.CharField(max_length=250)),
                ('expectation', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
