# Generated by Django 3.2.8 on 2023-07-12 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.CharField(choices=[['9 - 19', '9 - 19'], ['20 - 29', '20 - 29'], ['30 - 39', '30 - 39'], ['40 - 49', '40 - 49'], ['50 - 59', '50 - 59'], ['60+', '60+']], default='30 - 39', max_length=50)),
                ('sex', models.CharField(choices=[['9 - 19', '9 - 19'], ['20 - 29', '20 - 29'], ['30 - 39', '30 - 39'], ['40 - 49', '40 - 49'], ['50 - 59', '50 - 59'], ['60+', '60+']], default='female', max_length=50)),
                ('ethnicity', models.CharField(choices=[('African', 'African'), ('Asian', 'Asian'), ('Latin', 'Latin'), ('Pacific', 'Pacific'), ('Caucasian', 'Caucasian'), ('Other', 'Other')], default='Caucasian', max_length=50)),
                ('country', models.CharField(default='South Africa', max_length=100)),
                ('instructor', models.CharField(default='Nerine Jansen', max_length=250)),
                ('num_classes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('experience', models.CharField(choices=[['Very Good', 'Very Good'], ['Good', 'Good'], ['OK', 'OK'], ['Bad', 'Bad'], ['Very BAD', 'Very BAD']], default='Very Good', max_length=50)),
                ('quality', models.CharField(choices=[['Very Good', 'Very Good'], ['Good', 'Good'], ['OK', 'OK'], ['Bad', 'Bad'], ['Very BAD', 'Very BAD']], default='Very Good', max_length=50)),
                ('meat', models.CharField(choices=[['Yes, regularly', 'Yes, regularly'], ['Yes, sometimes', 'Yes, sometimes'], ['Yes, but only fish or seafood', 'Yes, but only fish or seafood'], ['No', 'No']], default='Yes, regularly', max_length=50)),
                ('diary', models.CharField(choices=[['Yes', 'Yes'], ['No', 'No']], default='Yes', max_length=50)),
                ('changes', models.CharField(choices=[['Eat less meat or seafood', 'Eat less meat or seafood'], ['Eat less dairy', 'Eat less dairy'], ['Eat less eggs', 'Eat less eggs'], ['Eat more plant foods', 'Eat more plant foods']], default='Eat more plant foods', max_length=50)),
                ('hard', models.CharField(choices=[['Eating out', 'Eating out'], ['Grocery shopping', 'Grocery shopping'], ['Food cravings', 'Food cravings'], ['Support from my family or friends', 'Support from my family or friends'], ['Making my own meals', 'Making my own meals'], ['Cost', 'Cost'], ['Other', 'Other']], max_length=50)),
                ('tell_a_friend', models.TextField()),
                ('improve', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
