# Generated by Django 3.2.8 on 2025-07-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_survey_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Psychic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('Mentor', 'Mentor'), ('Medium', 'Medium'), ('Healer', 'Healer'), ('Therapist', 'Therapist'), ('Numerologist', 'Numerologist')], max_length=100)),
                ('tagline', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Oncall', 'Oncall')], max_length=50)),
                ('status_at', models.DateTimeField()),
                ('psychic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='main.psychic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
