# Generated by Django 3.2.8 on 2025-07-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_day_psychic_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='role',
        ),
        migrations.AddField(
            model_name='psychic',
            name='img',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Oncall', 'Oncall')], max_length=50),
        ),
        migrations.AddField(
            model_name='psychic',
            name='roles',
            field=models.ManyToManyField(to='main.Role'),
        ),
    ]
