# Generated by Django 3.2.8 on 2025-07-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20250716_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='psychic',
            name='last_oncall_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychic',
            name='last_online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
