# Generated by Django 3.2.8 on 2025-07-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20250718_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychic',
            name='is_currently_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychic',
            name='latest_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='psychic',
            name='oncall_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychic',
            name='oncall_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='psychic',
            name='online_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychic',
            name='online_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='psychic',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='psychic',
            name='status_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychic',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
    ]
