# Generated by Django 3.2.8 on 2025-09-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20250721_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='prev_allowed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
