# Generated by Django 3.2.8 on 2025-10-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_backfill_prev_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayFastTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('m_payment_id', models.CharField(max_length=100)),
                ('pf_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(max_length=50)),
                ('name_first', models.CharField(blank=True, max_length=100, null=True)),
                ('name_last', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
