# Generated by Django 3.2.8 on 2025-10-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_payfasttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payfasttransaction',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payfasttransaction',
            name='m_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payfasttransaction',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
