# Generated by Django 5.2.8 on 2025-11-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
