# Generated by Django 5.2.8 on 2026-01-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_signup_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychic',
            name='is_currently_online',
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='latest_status',
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='oncall_count',
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='oncall_hours',
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='online_count',
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='online_hours',
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='score',
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='status_last_updated',
        ),
        migrations.RemoveField(
            model_name='psychic',
            name='total_hours',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Oncall', 'Oncall'), ('Fake Oncall', 'Fake Oncall')], max_length=50),
        ),
    ]
