name: Deploy to DigitalOcean

on:
  push:
    tags:
      - 'v*'  # Trigger on tags that start with "v"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add DigitalOcean host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "Known hosts file contents:"
          cat ~/.ssh/known_hosts

      - name: Debug SSH connection (optional)
        run: |
          ssh -o "StrictHostKeyChecking=yes" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'echo SSH connection successful!'

      - name: Deploy to DigitalOcean
        run: |
          ssh -o "StrictHostKeyChecking=yes" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bash -s' < ./scripts/deploy.sh
